# Generated by Django 5.2.4 on 2025-08-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_location_slug_alter_location_id_answeroption'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='input_type',
            field=models.CharField(choices=[('select', 'Seçmeli (Dropdown)'), ('text', 'Serbest Metin (Input)')], default='select', max_length=10),
        ),
    ]
