# Generated by Django 5.2.4 on 2025-08-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_question_input_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
